### ISSUE TITLE
DON'T FORGET TO "SLICE" NA JA

### ISSUE THREAD

**Issue by riflowth** [CPE34-A2/pre-freshy-2021#24]
@eltfshr SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE SLICE S

> **React STATE versus Array#slice**
> **React STATE versus Array#slice**
> **React STATE versus Array#slice**
> **React STATE versus Array#slice**

**Comment by eltfshr** [comment]
🔪🔲🔲🔲🔲🔲🔲

**Comment by riflowth** [comment]
@XiaoXuxxxx SLICE???!!!!!

**Comment by XiaoXuxxxx** [comment]
> @XiaoXuxxxx SLICE???!!!!!
s..s.. slic… SLICE!?

**Comment by XiaoXuxxxx** [comment]
> @XiaoXuxxxx SLICE???!!!!!

s..s.. slic… SLICE!?

**Comment by riflowth** [comment]
Now we know how to "SLICE" so this issue should be closed! @XiaoXuxxxx @eltfshr
