### ISSUE TITLE
Transaction system not working properly

### ISSUE THREAD

**Issue by riflowth** [CPE34-A2/pre-freshy-2021#27]
- They can reject their own Fuel transaction
- Confirm require seem bug

![image](https://user-images.githubusercontent.com/17198802/124522793-a72c1000-de1e-11eb-9eb2-9ffdc54f9d0d.png)

 @XiaoXuxxxx

**Comment by XiaoXuxxxx** [comment]
Every transaction can immediately discard by leader. The leader’s task page should show “DISCARD” only instead of “ACCEPT” and “REJECT” like the other member

**Comment by riflowth** [comment]
OHHHH, I got it thx
